[zh-cn]
  languageName = "Chinese-Simplified"
  contentDir = "content/zh-cn"
  weight = 5
  [zh-cn.params]
    languageISO = "zh-cn"
    languageTag = "zh-cn"
    footer = '由 <a class="text-muted" href="https://gethyas.com/">Hyas</a> 提供支持'
    alertText = ''

[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Brought to you by <a class="text-muted" href="https://gethyas.com/">Hyas</a>'
    alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'
